version: '3'

volumes:
  hostel-DB:

services:
  app:
    build: .
    ports:
      - 8080:8080
    container_name: app
    links:
      - activemq
  activemq:
    image: rmohr/activemq
    ports:
      - 1883:1883
      - 5672:5672
      - 8161:8161
      - 61613:61613
      - 61614:61614
      - 61616:61616